# Generated by Django 4.0.6 on 2022-08-14 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_category_post_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
